//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

pub use super::comment::Entity as Comment;
pub use super::image_vote::Entity as ImageVote;
pub use super::images::Entity as Images;
pub use super::room::Entity as Room;
pub use super::user::Entity as User;
