//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::comment::Entity")]
    Comment,
    #[sea_orm(has_many = "super::image_vote::Entity")]
    ImageVote,
    #[sea_orm(has_many = "super::images::Entity")]
    Images,
}

impl Related<super::comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comment.def()
    }
}

impl Related<super::image_vote::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImageVote.def()
    }
}

impl Related<super::images::Entity> for Entity {
    fn to() -> RelationDef {
        super::image_vote::Relation::Images.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::image_vote::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
